### ISSUE TITLE
Can not select multiple Processor Architectures

### ISSUE THREAD

**Issue by SomeGuyWW** [WinWorldPC/adventure#56]
I can not select multiple Processor Architectures when editing a download.

For example, when editing "Microsoft Windows NT 4.0 Workstation (4.00.1381.1) [Korean] (ISO)"
https://winworldpc.com/sa/download/e160cb5a-5c3e-11e8-8d2a-fa163e9022f0

It is supposed to be x86-32, ppc, MIPS, Alpha

but when I select them and submit it says "The download can not be edited"

**Comment by NattyNarwhal** [comment]
```
May 20 17:26:27 sunnyvale nodejs[1427]: { Error: Data truncated for column 'Arch' at row 1
May 20 17:26:27 sunnyvale nodejs[1427]:     at Packet.asError (/opt/winworld/adventure/adventure/node_modules/mysql2/lib/packets/packet.js:713:13)
May 20 17:26:27 sunnyvale nodejs[1427]:     at Execute.Command.execute (/opt/winworld/adventure/adventure/node_modules/mysql2/lib/commands/command.js:28:22)
May 20 17:26:27 sunnyvale nodejs[1427]:     at PoolConnection.Connection.handlePacket (/opt/winworld/adventure/adventure/node_modules/mysql2/lib/connection.js:502:28)
May 20 17:26:27 sunnyvale nodejs[1427]:     at PacketParser.onPacket (/opt/winworld/adventure/adventure/node_modules/mysql2/lib/connection.js:81:16)
May 20 17:26:27 sunnyvale nodejs[1427]:     at PacketParser.executeStart (/opt/winworld/adventure/adventure/node_modules/mysql2/lib/packet_parser.js:77:14)
May 20 17:26:27 sunnyvale nodejs[1427]:     at Socket.<anonymous> (/opt/winworld/adventure/adventure/node_modules/mysql2/lib/connection.js:89:29)
May 20 17:26:27 sunnyvale nodejs[1427]:     at emitOne (events.js:116:13)
May 20 17:26:27 sunnyvale nodejs[1427]:     at Socket.emit (events.js:211:7)
May 20 17:26:27 sunnyvale nodejs[1427]:     at addChunk (_stream_readable.js:263:12)
May 20 17:26:27 sunnyvale nodejs[1427]:     at readableAddChunk (_stream_readable.js:250:11)
May 20 17:26:27 sunnyvale nodejs[1427]:   code: 'WARN_DATA_TRUNCATED',
May 20 17:26:27 sunnyvale nodejs[1427]:   errno: 1265,
May 20 17:26:27 sunnyvale nodejs[1427]:   sqlState: '01000',
May 20 17:26:27 sunnyvale nodejs[1427]:   sqlMessage: 'Data truncated for column \'Arch\' at row 1' }
```

**Comment by NattyNarwhal** [comment]
An ugly workaround's been put in place. I may need to file a bug with the upstream mysql2 module, if I can triage.

**Comment by nitinseshadri** [comment]
@SomeGuyWW A screenshot would help. Trying to access the link above simply says "You are not allowed to access this route."*, because I am (obviously) not an admin of WinWorld.

*Nitpick: @NattyNarwhal rather than saying 'route' you should say 'page' or 'part of the site'. The word 'route' would seem confusing to the user. So the message should say [ You're don't have permission to access this page. [Return to WinWorld](http://www.winworldpc.com/) ] with a link.
